all: polla

polla:
	gcc -o pollis pollitos.c -lpthread

polla2:
	gcc -o pollis2 pollitos2.c -lpthread

clean:
	rm -rf pollis pollis2

debug:
	gcc -g pollitos.c -lpthread

debug2:
	gcc -g pollitos2.c -lpthread
